import React, {Component} from 'react';
import './App.css';
import Person from './Person/Person';

class App extends Component {
  
  state = {
    person : [
      {name:'Max', age:'29'},
      {name:'Bob', age:'19'},
      {name:'Mark', age:'15'},
    ],
    something: 'hello'
  }
 
  switchNameHandler = (newName) => {
    this.setState(
      {
        person : [
          {name: newName, age:'29'},
          {name:'Bob', age:'19'},
          {name:'Mark', age:'55'},
        ]
      }
    );
  };
  
  // The Event interface represents an event which takes place in the DOM.An event can be triggered by the user action e.g. clicking the mouse button or tapping keyboard, or generated by APIs to represent the progress of an asynchronous task.

  // The target property of the Event interface is a reference to the object onto which the event was dispatched. The event.target property can be used in order to implement event delegation.
    // DOM event delegation is a mechanism of responding to ui-events via a single common parent rather than each child, through the magic of event "bubbling" (aka event propagation).
  // The event.target is a reference to the object that dispatched the event. Or in other words, it identifies the HTML element on which the event occurred.

  // an event listen listener is something that listens for an event.
  //  Here are some of the common JavaScript events:
    // change:: An HTML element has been changed
    // click:: The user clicks an HTML element
    // mouseover:: The user moves the mouse over an HTML element
    // mouseout:: The user moves the mouse away from an HTML element
    // keydown:: The user pushes a keyboard key
    // load:: The browser has finished loading the page

  // thus, this 'event' objeject will automatically be passed to this method
  nameChangedHandler = (event) => {
    this.setState(
      {
        person : [
          {name: 'Max', age:'29'},
          // extracting the value from target element ie input box.
          {name: event.target.value , age:'19'},
          {name:'Mark', age:'55'},
        ]
      }
    );
  };
  

  render() {
    return (
      <div className="App">
        <h1>Hello world of React!!!</h1>
        <Person  
          name={this.state.person[0].name}
          age={this.state.person[0].age}
        />
        {/* as we want 'bob' should only be changed with username. hence here only passing out params for inputbox */}
        <Person 
          name={this.state.person[1].name} 
          age={this.state.person[1].age}
          changed={this.nameChangedHandler}
        />
        <Person 
          name={this.state.person[2].name} 
          age={this.state.person[2].age}
          click={this.switchNameHandler.bind(this, 'Alex')}> My Hobbies : Soccer, Cricket  
        </Person>
        <button  onClick={this.switchNameHandler.bind(this, 'Dark')}>Switch Names</button>
      </div>

    );
  }
}
export default App;


